export enum errorTypes {
    GENERAL_ERROR = "GENERAL_ERROR",
    GENERAL_ERROR_INVERSE = "GENERAL_ERROR_INVERSE",
    FIND_ONE = "FIND_ONE",
    INSERT_ONE = "INSERT_ONE",
    INSERT_ONE_OBJECT_WITH_IMAGES = "INSERT_ONE_OBJECT_WITH_IMAGES",
    UPDATE_ONE = "UPDATE_ONE",
    UPDATE_MANY = "UPDATE_MANY",
    DELETE_ONE = "DELETE_ONE",
    DELETE_MANY = "DELETE_MANY"
}
